ASP.NET/Bike Store/BikeDemo/BikeDemo/Controllers/BikesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BikeDemo;
using BikeDemo.Models;

namespace BikeDemo.Controllers
{
    public class BikesController : Controller
    {
        private BikeEntities db = new BikeEntities();

        // GET: Bikes
        public ActionResult Index()
        {
            var productCategories = from p in db.ProductCategories
                                    where p.ParentProductCategoryID == 1
                                    select p;
            
            return View(productCategories.ToList());
        }

        // GET: Bikes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var productCategory = from b in db.Products
                                  where b.ProductModelID == id
                                  select b;
            if (productCategory == null)
            {
                return HttpNotFound();
            }

            var rev = from r in db.ProductReviews
                      where r.productID == id
                      select r;

            List<ProductReview> reviews = new List<ProductReview>();

            foreach (var review in rev)            
                reviews.Add(review);

            ViewBag.review = reviews;

            return View(productCategory.ToList());
        }

        // GET: Bikes/Create
        public ActionResult Create()
        {
            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name");
            return View();
        }

        // POST: Bikes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductCategoryID,ParentProductCategoryID,Name,rowguid,ModifiedDate")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.ProductCategories.Add(productCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", productCategory.ParentProductCategoryID);
            return View(productCategory);
        }

        // GET: Bikes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", productCategory.ParentProductCategoryID);
            return View(productCategory);
        }

        // POST: Bikes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductCategoryID,ParentProductCategoryID,Name,rowguid,ModifiedDate")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", productCategory.ParentProductCategoryID);
            return View(productCategory);
        }

        // GET: Bikes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: Bikes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductCategory productCategory = db.ProductCategories.Find(id);
            db.ProductCategories.Remove(productCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Road()
        {

            return GetByType(6);
        }

        public ActionResult Touring()
        {

            return GetByType(7);

        }

        public ActionResult Mountain()
        {

            return GetByType(5);
        }
       
        public ActionResult GetByType(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var roadQuery = (from p in db.vProductAndDescriptions
                             where p.ProductCategoryID == id && p.SellEndDate == null && p.Culture == "en"
                             select new { p.ProductModel, p.Description, p.ProductModelID }).Distinct();
            List<BikeListModel> list = new List<BikeListModel>();
            foreach (var d in roadQuery)
                list.Add(new BikeListModel(d.ProductModel, d.Description, d.ProductModelID));

            return View(list);
        }


    }

}

ASP.NET/Bike Store/BikeDemo/BikeDemo/Controllers/GearController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BikeDemo;
using BikeDemo.Models;

namespace BikeDemo.Controllers
{
    public class GearController : Controller
    {
        private BikeEntities db = new BikeEntities();


        public ActionResult Index()
        {
            var productCategories = from p in db.ProductCategories
                                    where p.ProductCategoryID >= 2 && p.ProductCategoryID <=4 
                                    select p;

            return View(productCategories.ToList());
        }

        public ActionResult ProductList(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var productCategory = from b in db.Products
                                  where b.ProductCategoryID == id && b.SellEndDate == null
                                  select b;
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public ActionResult Components()
        {
            return GetByType(2);
        }

        public ActionResult Clothing()
        {

            return GetByType(3);
        }

        public ActionResult Accessories()
        {
            return GetByType(4);
        }

        public ActionResult GetByType(int? id)
        {
            var gear = from a in db.ProductCategories
                       where (from o in db.Products where o.SellEndDate == null select o.ProductCategoryID).Contains(a.ProductCategoryID)
                       && a.ParentProductCategoryID == id
                       select a;
            return View(gear.ToList());
        }










    }


}

ASP.NET/Bike Store/BikeDemo/BikeDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaptchaMvc.HtmlHelpers;
using System.Net.Mail;
using System.Net;


namespace BikeDemo.Controllers
{
    public class HomeController : Controller
    {
        private BikeEntities db = new BikeEntities();
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Error()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        // GET: Manager 
        public ActionResult ManagerCreate()
        {
            return View();
        }

        // GET: Manager Recover
        public ActionResult ManagerRecover()
        {
            return View();
        }

        //POST: Manger Recover
        [HttpPost]
        public ActionResult ManagerRecover([Bind(Include = "Email")] string email)
        {
            if (ModelState.IsValid)
            {
                string conf = "";
                var query = from m in db.Managers
                            where m.Email == email
                            select m;

                if (query.Any())
                {
                    foreach (Manager man in query)
                        conf = man.ConfCode.ToString();
                    MailAddress to = new MailAddress(email);
                    string body = "A request to reset your password has been sent. If this was you click the link below.\n If this was not done by you, ignore this email.\n http://localhost:16700/Home/PasswordReset/?conf=" + conf;
                    string subject = "Password Reset - DO NOT REPLY";
                    MailAddress replyToEmail = new MailAddress("compscimilestone@gmail.com");

                    sendEmail(to, body, subject, replyToEmail);

                    TempData["message"] = "Email has been sent to " + email;
                }
                else
                    TempData["message"] = "User does not exist";
            }
            ViewBag.email = email;
            return View();
        }

        public ActionResult PasswordReset()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PasswordReset([Bind(Include = "Password")] string pass)
        {
            if (ModelState.IsValid)
            {
                string conf = Request.QueryString["conf"];

                var query = from m in db.Managers
                            where m.ConfCode.ToString() == conf
                            select m;

                if (query.Any())
                {
                    foreach (Manager man in query)
                        man.Password = pass;

                    try
                    {
                        db.SaveChanges();
                    }
                    catch (Exception)
                    {
                        TempData["error"] = "An error has occured. Please try again later";
                    }
                }
                else
                    TempData["message"] = "User does not exist";
            }
            return View();
        }

        public ActionResult ValidateEmail()
        {
            string conf = Request.QueryString["conf"];

            var query = from r in db.Managers
                      where r.ConfCode.ToString() == conf
                      select r;

            if (query.Any())
            {
                foreach (Manager manager in query)
                    manager.Confirmed = 1;

                try
                {
                    db.SaveChanges();
                }
                catch(Exception)
                {
                    TempData["error"] = "An error has occured. Please try again later.";
                }
            }
            else
                TempData["error"] = "An error has occured. Please try again later.";

            return View();
        }

        // GET: Manager Login
        public ActionResult ManagerLogin()
        {
            return View();
        }

        public ActionResult ManagerLogout()
        {
            Session.Abandon();

            return RedirectToAction("Index");
        }

        //POST: Manager Login
        [HttpPost]
        public ActionResult ManagerLogin([Bind(Include = "Email, Password")] Manager man)
        {
            if (ModelState.IsValid)
            {
                var query = from m in db.Managers
                            where m.Email == man.Email && m.Password == man.Password
                            select m;

                if (query.Any())
                {
                    Session["loggedIn"] = true;
                    Session["email"] = man.Email;

                   return RedirectToAction("Index");
                }
            }
            return View();
        }

        // POST: Manager Create
        [HttpPost]
        public ActionResult ManagerCreate([Bind(Include = "Email, Password")] Manager man)
        {
            if (ModelState.IsValid)
            {
                man.ConfCode = Guid.NewGuid();
                db.Managers.Add(man);
                db.SaveChanges();

                string body = "Please confirm your email by clicking the following link: http://localhost:16700/Home/ValidateEmail/?conf=" + man.ConfCode;
                MailAddress email = new MailAddress(man.Email);
                MailAddress replyToEmail = new MailAddress("compscimilestone@gmail.com");
                string subject = "Validate Email -  DO NOT REPLY";

                sendEmail(email, body, subject, replyToEmail);
            }
            return View();
        }

        public ActionResult Search(string filters)
        {
            string s = filters;
            // Split string on spaces.
            // ... This will separate all the words.
            string[] fwords = s.Split(' ');
            string single = fwords[0];
            
            //var pquery = db.Products
            //    .Where(p => p.Name
             //                .Contains(fwords[0]));



            //var products = from b in pquery select b;

            var products = from c in db.Products
                         where c.Name.IndexOf(single) >= 0
                         select c;

            return View(products.ToList());
        }

       
        [HttpPost]

        public ActionResult Contact(string empty, BikeDemo.Models.ContactModel CM)
        {
            if (this.IsCaptchaValid("Captcha is not valid"))
            {
                try
                {
                    MailAddress email = new MailAddress(CM.email, CM.fName + " " + CM.lName);
                    string body = "First name: " + CM.fName + "\n" + "Last Name: " + CM.lName + "\n" + "Email: " + CM.email
                        + "\n" + "Comment: " + CM.comments;
                    string subject = "Hello There";
                    MailAddress replyToEmail = email;

                    sendEmail(email, body, subject, replyToEmail);

                    return RedirectToAction("Success");
                }
                catch (Exception)
                {
                    return RedirectToAction("Error");
                }

            }

            TempData["ErrorMessage"] = "Error: captcha is not valid.";
            return View();

        }

        public void sendEmail(MailAddress email, string body, string subject, MailAddress replyToEmail)
        {
            MailMessage msg = new MailMessage();
            SmtpClient smtp = new SmtpClient();
            //TODO: Setup Message
            //Add a Reply-to the message having the inputted user's email

            msg.From = new MailAddress("compscimilestone@gmail.com", "Administrator");
            msg.To.Add(email);
            msg.Subject = subject;
            msg.Body = body;
            msg.ReplyToList.Add(replyToEmail);

            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;
            smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
            smtp.Credentials = new NetworkCredential("compscimilestone@gmail.com", "somepassword");
            smtp.Send(msg);
            msg.Dispose();
        }
    }
}

ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title Us</h2>

<br/>
<br/>
<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
    magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut 
    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit 
    esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, 
    sunt in culpa qui officia deserunt mollit anim id est laborum.<br/><br/>
    
    <b>Our Team:</b><br/>
    Geoff Shapiro, the CEO of the company has been involved in the cyclist community for years<br/>
    and is the brains behind all of our new models.</p>

ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/Contact.cshtml
@model BikeDemo.Models.ContactModel

@using CaptchaMvc.HtmlHelpers;


@{
    ViewBag.Title = "Contact";
}

<h2>Contact</h2>

<address>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <table border="0" cellspacing="1">
            <tbody>
                <tr>
                    <td style="width:130px" valign="top">
                        First Name:
                        @*@Html.LabelFor(model => model.FirstName) *@
                    </td>
                    <td colspan="2">
                        @Html.TextBoxFor(model => model.fName, new { size = "35" })
                      
                        @Html.ValidationMessageFor(model => model.fName, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td style="width:130px" valign="top">
                        Last Name:
                    </td>
                    <td colspan="2">
                        @Html.TextBoxFor(model => model.lName, new { size = "35" })
                        @Html.ValidationMessageFor(model => model.lName, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td style="width:130px" valign="top">
                        Email:
                    </td>
                    <td colspan="2">
                        @Html.TextBoxFor(model => model.email, new { size = "35", @type = "email" })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td style="width:130px" valign="top">
                        Comments:
                    </td>
                    <td valign="top">
                        @Html.TextAreaFor(model => model.comments, new { cols = "40", rows = "10" })
                        @Html.ValidationMessageFor(model => model.comments, "", new { @class = "text-danger" })

                    </td>
                </tr>
                <tr>
                    <td valign="top">
                        &nbsp;
                    </td>
                    <td colspan="2">
                        @Html.Captcha(6) 
                        <button type="submit">Submit</button>
                        <button type="submit">Reset</button>
                    </td>
                </tr>
            </tbody>
        </table>
    }
</address>

ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <a href='@Url.Action("Index", "Bikes")'>
        <img src="@Url.Content("~/Content/AOBC.png")" alt="IMAGES" />
    </a>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Bikes</h2>
        <p>
            The widest selection of mountain, road and touring bikes online. The best brands and models always at the best prices.
        </p>
        <p>@Html.ActionLink("Browse Bikes", "Index", "Bikes", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>Gear</h2>
        <p>Get the best equipment here. High quality gear for the true bike fanatics from handle bars to vest we truly have everything.</p>
        <p>@Html.ActionLink("Browse Gear", "Index", "Gear", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>Accessories</h2>
        <p>Bike Racks, Bike Stands, Bottles and Cages, Cleaners, Fenders, Tires and Tubes. Everything at the click of a button. </p>
        <p>@Html.ActionLink("Browse Accessories", "Accessories", "Gear", null, new { @class = "btn btn-default" })</p>
    </div>
</div>


ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/ManagerCreate.cshtml
@model BikeDemo.Manager

@{
    ViewBag.Title = "ManagerCreate";
}

<h2>ManagerCreate</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Manager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @type="password", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/ManagerLogin.cshtml
@model BikeDemo.Manager

@{
    ViewBag.Title = "ManagerLogin";
}

<h2>ManagerLogin</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Manager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @type="password", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" /> @Html.ActionLink("Register", "ManagerCreate", "Home")
                <br />
                @Html.ActionLink("Account Recovery", "ManagerRecover", "Home")
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/ManagerRecover.cshtml
@{
    ViewBag.Title = "ManagerRecover";
    string email = ViewBag.email == null ? "" : ViewBag.email;
}

<h2>ManagerRecover</h2>
<p>@TempData["message"]</p>
@using (Html.BeginForm()) { 
    <table>
        <tr>
            <td>
                <label>Enter Your Email: </label>
            </td>
            <td>
                <input type="email" name="email" required value="@email" />
            </td>
        </tr>
    </table>
    <input type="submit" value="Recover Account" />
}


ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/PasswordReset.cshtml
@{
    ViewBag.Title = "PasswordReset";
}

<h2>PasswordReset</h2>

<p>@TempData["error"]</p>
<p>@TempData["Message"]</p>

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>
                <label>Enter a new password: </label>
            </td>
            <td>
                <input type="password" name="pass" />
            </td>
        </tr>
    </table>
    <input type="submit" value="Reset Passowrd" />
}

ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/Search.cshtml
@model IEnumerable<BikeDemo.Product>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StandardCost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ListPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Size)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SellStartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SellEndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiscontinuedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThumbnailPhotoFileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rowguid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductCategory.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductModel.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StandardCost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ListPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Size)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SellStartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SellEndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiscontinuedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThumbnailPhotoFileName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rowguid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductCategory.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductModel.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductID })
        </td>
    </tr>
}

</table>

ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/Success.cshtml

@{
    ViewBag.Title = "Success";
}

<h2>Success in contacting us</h2>


ASP.NET/Bike Store/BikeDemo/BikeDemo/Views/Home/ValidateEmail.cshtml

@{
    ViewBag.Title = "Validate Email";

    var message = TempData["error"] == null ? "Your email is now validated." : TempData["error"];
}

<h2>Validate Email</h2>

<p>@message</p>